--
- hosts: localhost
  become: true
  tasks:
      - name: Install fail2ban packages
      yum: name={{item}} state=latest update_cache=yes
      with_items:
        - fail2ban
        - fail2ban-systemd
      
      - name: Copy fail2ban jail.local to its final home
      copy: src=configs/prod/security/jail.local dest=/etc/fail2ban/jail.local mode=0700

      - name: Ensure fail2ban starts and is enabled by default
      service: name=fail2ban state=started enabled=yes
