--
- hosts: localhost
  become: true
  tasks:
    - name: Install fail2ban packages
      yum: name={{item}} state=latest update_cache=yes
      with_items:
        - fail2ban
        - fail2ban-systemd
        - jwhois
      
    - name: Copy fail2ban jail.local to its final home
      copy: src=jail.local dest=/etc/fail2ban/jail.local mode=0700
      
    - name: Ensure firewalld starts and is enabled by default
      service: name=firewalld state=started enabled=yes

    - name: Ensure fail2ban starts and is enabled by default
      service: name=fail2ban state=started enabled=yes
